
name: Run main.py and commit changes

on:
  # push:
  workflow_dispatch:  # 手动触发

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有历史记录
      - name: Remove ignored files
        run: |
          while IFS= read -r file; do
              if [ -e "$file" ]; then
                  echo "Deleting: $file"
                  rm -rf "$file" || echo "Failed to delete: $file"
              else
                  echo "File not found: $file"
              fi
          done < <(grep -v '^#' .gitignore | grep -v '^$')


      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # 如果有依赖
      - name: Run main.py
        run: python main.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add problems
          git commit -m "Automated commit" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
